# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_ga_web_page_views'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Version of dbt
require-dbt-version: ">=0.18.1"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
vars:
  potato_tags: ubi

models:
    dbt_ga_web_page_views:
      # Applies to all files under models/example/
      staging:
        materialized: view
        bind: false
      core:
        materialized: table

seeds:
  dbt_ga_web_page_views:
    +enabled: true
    +schema: seed_data
    potato:
      +tags:
        - '{{ var("potato_tags") }}'
    apple:
      +enabled: false
